/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTemplate;

import static FormTemplate.CenterPanel.tblActSet;
import static FormTemplate.CenterPanel.tblInputTraceList;
import Helper.Common.MessageHelper;
import Helper.Common.Variables;
import Helper.Dashboard.AutoGenerateHelper;
import TableHelper.TableController;
import static TableHelper.TableController.InitTableFromListString;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.LinkedList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import static Helper.Dashboard.AutoGenerateHelper.GenerateTraceRandomize;
import static Helper.Dashboard.AutoInsertTraceHelper.GenerateFromLog;

/**
 *
 * @author phamdinhlam
 */
public class AutoInsertTrace extends javax.swing.JFrame {

    /**
     * Creates new form AutoInsertTrace
     */
    public AutoInsertTrace() {
        initComponents();
        Initialize();
        LoadActivitySetToCombobox(cmbBeginActivity);
        
    }
    public void Initialize() 
    {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2 - 200);
        this.setResizable(false);
        
    }
    
    public static void LoadActivitySetToCombobox(JComboBox _JComboBox)
    {
        Integer rows = tblActSet.getRowCount();
        if (rows == 0)
        {
            MessageHelper.Warning("The activity set table is empty. Please load activity set table first!");
            return;
        }
        _JComboBox.removeAllItems();
        _JComboBox.addItem("START");
        for(Integer i=0; i<rows; i++)
        {
            Object currentObj = tblActSet.getValueAt(i, 0);
            String currentAct = "";
            if(currentObj!=null)
            {
                currentAct = currentObj.toString();
                _JComboBox.addItem(currentAct);
                
            }
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbBeginActivity = new javax.swing.JComboBox<>();
        txtNumberTraces = new javax.swing.JTextField();
        cmbNumberSteps = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        lblInsertFromLog = new javax.swing.JLabel();
        txtFromTrace = new javax.swing.JTextField();
        lblAutoGenerateTraces = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Input parameter"));

        jLabel2.setText("Number steps:");

        jLabel3.setText("Begin activity:");

        jLabel1.setText("Total traces:");

        cmbBeginActivity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "activityX" }));

        txtNumberTraces.setText("10");
        txtNumberTraces.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumberTracesActionPerformed(evt);
            }
        });

        cmbNumberSteps.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "20", "50", "90", "100" }));
        cmbNumberSteps.setSelectedIndex(3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(157, 157, 157)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumberTraces, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbNumberSteps, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbBeginActivity, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 45, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cmbNumberSteps, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(cmbBeginActivity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNumberTraces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Generate type"));

        jLabel6.setText("From trace:");

        lblInsertFromLog.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        lblInsertFromLog.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-plus.png"))); // NOI18N
        lblInsertFromLog.setText("Generate from log");
        lblInsertFromLog.setToolTipText("Show selected trace in table");
        lblInsertFromLog.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInsertFromLog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInsertFromLogMousePressed(evt);
            }
        });

        txtFromTrace.setText("10");
        txtFromTrace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFromTraceActionPerformed(evt);
            }
        });

        lblAutoGenerateTraces.setFont(new java.awt.Font("Lucida Grande", 1, 11)); // NOI18N
        lblAutoGenerateTraces.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-plus.png"))); // NOI18N
        lblAutoGenerateTraces.setText("Random generate");
        lblAutoGenerateTraces.setToolTipText("Show selected trace in table");
        lblAutoGenerateTraces.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAutoGenerateTraces.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAutoGenerateTracesMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblAutoGenerateTraces, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertFromLog, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFromTrace, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtFromTrace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblInsertFromLog, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(lblAutoGenerateTraces, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblAutoGenerateTracesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAutoGenerateTracesMousePressed
        // TODO add your handling code here:
        
        try {
            Integer steps = Integer.parseInt(cmbNumberSteps.getSelectedItem().toString());
            Integer numberTraces = Integer.parseInt(txtNumberTraces.getText());
            String activity = cmbBeginActivity.getSelectedItem().toString();
            List<String> outputTraceList = new LinkedList<>();
            outputTraceList = GenerateTraceRandomize(steps, numberTraces, activity, tblActSet);
            
            if(InitTableFromListString(tblInputTraceList, outputTraceList))
            {
                Variables.stepInForPredictESN = steps;
                this.dispose();
            }
                
            
        } catch (Exception e) {
            MessageHelper.Error(e.toString());
        }
        

    }//GEN-LAST:event_lblAutoGenerateTracesMousePressed

    private void txtNumberTracesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumberTracesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumberTracesActionPerformed

    private void lblInsertFromLogMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsertFromLogMousePressed
        // TODO add your handling code here:
//        (Integer _numberStep, String _beginAct, Integer _fromTrace, Integer _totalTrace)
        try {
            Integer steps = Integer.parseInt(cmbNumberSteps.getSelectedItem().toString());
            Integer numberTraces = Integer.parseInt(txtNumberTraces.getText());
            String activity = cmbBeginActivity.getSelectedItem().toString();
            Integer fromTrace = Integer.parseInt(txtFromTrace.getText());
            List<String> outputTraceList = new LinkedList<>();
            outputTraceList = GenerateFromLog(steps, activity, fromTrace, numberTraces);
            
            if(InitTableFromListString(tblInputTraceList, outputTraceList))
            {
                Variables.stepInForPredictESN = steps;
                this.dispose();
            }
            
        } catch (Exception e) {
            MessageHelper.Error(e.toString());
        }
    }//GEN-LAST:event_lblInsertFromLogMousePressed

    private void txtFromTraceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFromTraceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFromTraceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoInsertTrace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoInsertTrace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoInsertTrace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoInsertTrace.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmbBeginActivity;
    public static javax.swing.JComboBox<String> cmbNumberSteps;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    public static javax.swing.JLabel lblAutoGenerateTraces;
    public static javax.swing.JLabel lblInsertFromLog;
    public static javax.swing.JTextField txtFromTrace;
    public static javax.swing.JTextField txtNumberTraces;
    // End of variables declaration//GEN-END:variables
}
