/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTemplate;

import Helper.Common.MessageHelper;
import Helper.Common.OpenRecently;
import Helper.Common.Variables;
import static Helper.Common.Variables.frmSNA;
import static Helper.Common.Variables.functionManagerFrame;
import static Helper.Common.Variables.globalGraph;
import static Helper.Common.Variables.globalXESLogListStrings;
import static Helper.Common.Variables.steadyGraph;
import static Helper.Dashboard.FunctionManagerHelper.DisplayFunctionList;
import Helper.Dashboard.LeftPanelHelper;
import SNAHelper.FormatGraph;
import ThreadController.CalculateGraphCentrality;
import ThreadController.ReadFileController;
import ThreadController.SaveFileController;
import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import static Helper.GraphStream.MakeSteadyGraph.RecoveryEssentialEdge;
import org.graphstream.graph.Graph;

/**
 *
 * @author phamdinhlam
 */
public class LeftPanel extends javax.swing.JPanel {

    /**
     * Creates new form RightPanel
     */
    public LeftPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        lblOpenRawFile = new javax.swing.JLabel();
        lblSave = new javax.swing.JLabel();
        lblFormatGraph = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblFunctionManager = new javax.swing.JLabel();
        lblTraindModel = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        lblViewSNAWindows = new javax.swing.JLabel();
        lblOpenrecently = new javax.swing.JLabel();
        icnDiscovery = new javax.swing.JLabel();
        advanceGraphView = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblExprotESN = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        systemProcessingBar = new javax.swing.JProgressBar();

        jLabel2.setText("jLabel2");

        setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 255)));
        setForeground(new java.awt.Color(102, 102, 255));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 10)); // NOI18N
        jLabel1.setText("Predictive Process-aware organize social network");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblOpenRawFile.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblOpenRawFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-opened_folder.png"))); // NOI18N
        lblOpenRawFile.setText("Open");
        lblOpenRawFile.setToolTipText("Open raw data file");
        lblOpenRawFile.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblOpenRawFile.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpenRawFile.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblOpenRawFile.setIconTextGap(1);
        lblOpenRawFile.setName(""); // NOI18N
        lblOpenRawFile.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblOpenRawFile.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenRawFileMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOpenRawFileMousePressed(evt);
            }
        });

        lblSave.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-save.png"))); // NOI18N
        lblSave.setText("Save log");
        lblSave.setToolTipText("Load saved case study");
        lblSave.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSave.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSave.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSave.setIconTextGap(1);
        lblSave.setName(""); // NOI18N
        lblSave.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSave.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSaveMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveMouseClicked(evt);
            }
        });

        lblFormatGraph.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblFormatGraph.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-window_settings_filled.png"))); // NOI18N
        lblFormatGraph.setText("Setting");
        lblFormatGraph.setToolTipText("Format graph in main dashboard");
        lblFormatGraph.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblFormatGraph.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFormatGraph.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFormatGraph.setIconTextGap(1);
        lblFormatGraph.setName(""); // NOI18N
        lblFormatGraph.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblFormatGraph.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFormatGraphMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFormatGraphMousePressed(evt);
            }
        });

        lblFunctionManager.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblFunctionManager.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-graph_report.png"))); // NOI18N
        lblFunctionManager.setText("Function");
        lblFunctionManager.setToolTipText("Function manager");
        lblFunctionManager.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblFunctionManager.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFunctionManager.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFunctionManager.setIconTextGap(1);
        lblFunctionManager.setName(""); // NOI18N
        lblFunctionManager.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblFunctionManager.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFunctionManagerMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFunctionManagerMouseClicked(evt);
            }
        });

        lblTraindModel.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblTraindModel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-animation_rig.png"))); // NOI18N
        lblTraindModel.setText("View Trained");
        lblTraindModel.setToolTipText("View trained model");
        lblTraindModel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTraindModel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTraindModel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTraindModel.setIconTextGap(1);
        lblTraindModel.setName(""); // NOI18N
        lblTraindModel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblTraindModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTraindModelMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTraindModelMouseClicked(evt);
            }
        });

        lblViewSNAWindows.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblViewSNAWindows.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-social_network.png"))); // NOI18N
        lblViewSNAWindows.setText("<Html>\n<p align=\"center\">\nCentrality<br> analisys\n</p>");
        lblViewSNAWindows.setToolTipText("Analyze the centrality of actors in graph");
        lblViewSNAWindows.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblViewSNAWindows.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblViewSNAWindows.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblViewSNAWindows.setIconTextGap(1);
        lblViewSNAWindows.setName(""); // NOI18N
        lblViewSNAWindows.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblViewSNAWindows.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblViewSNAWindowsMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblViewSNAWindowsMouseClicked(evt);
            }
        });

        lblOpenrecently.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblOpenrecently.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-overtime.png"))); // NOI18N
        lblOpenrecently.setText("Open recently");
        lblOpenrecently.setToolTipText("Load saved case study");
        lblOpenrecently.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblOpenrecently.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOpenrecently.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblOpenrecently.setIconTextGap(1);
        lblOpenrecently.setName(""); // NOI18N
        lblOpenrecently.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblOpenrecently.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOpenrecentlyMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblOpenrecentlyMouseClicked(evt);
            }
        });

        icnDiscovery.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        icnDiscovery.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-ICN.png"))); // NOI18N
        icnDiscovery.setText("<Html> <p align=\"center\"> ICN<br> Discovery </p>");
        icnDiscovery.setToolTipText("Discover ICN model from log");
        icnDiscovery.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        icnDiscovery.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        icnDiscovery.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        icnDiscovery.setIconTextGap(1);
        icnDiscovery.setName(""); // NOI18N
        icnDiscovery.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        icnDiscovery.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                icnDiscoveryMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icnDiscoveryMouseClicked(evt);
            }
        });

        advanceGraphView.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        advanceGraphView.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-genealogy.png"))); // NOI18N
        advanceGraphView.setText("<Html> <p align=\"center\"> Advance<br> mining </p>");
        advanceGraphView.setToolTipText("Discover ICN model from log");
        advanceGraphView.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        advanceGraphView.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        advanceGraphView.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        advanceGraphView.setIconTextGap(1);
        advanceGraphView.setName(""); // NOI18N
        advanceGraphView.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        advanceGraphView.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                advanceGraphViewMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                advanceGraphViewMouseClicked(evt);
            }
        });

        lblExprotESN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8_network_25px.png"))); // NOI18N
        lblExprotESN.setText("Export");
        lblExprotESN.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExprotESN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblExprotESNMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExprotESN)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblExprotESN)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblViewSNAWindows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFunctionManager)
                    .addComponent(lblOpenRawFile))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblOpenrecently)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblSave)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblFormatGraph)
                                .addGap(42, 42, 42))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblTraindModel)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(icnDiscovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(advanceGraphView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))))
            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblOpenRawFile)
                    .addComponent(lblFormatGraph)
                    .addComponent(lblOpenrecently)
                    .addComponent(lblSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblFunctionManager, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblTraindModel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblViewSNAWindows, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(icnDiscovery, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(advanceGraphView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        lblOpenRawFile.getAccessibleContext().setAccessibleDescription("");
        lblSave.getAccessibleContext().setAccessibleDescription("");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(systemProcessingBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(74, Short.MAX_VALUE)
                .addComponent(systemProcessingBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(24, 24, 24)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void lblOpenRawFileMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenRawFileMouseClicked
        
        

    }//GEN-LAST:event_lblOpenRawFileMouseClicked

    private void lblSaveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMouseClicked
        // TODO add your handling code here:
       
    }//GEN-LAST:event_lblSaveMouseClicked

    private void lblOpenRawFileMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenRawFileMousePressed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            LeftPanelHelper.OpenRawDataFile();
        } catch (IOException ex) {
            MessageHelper.Error(ex.toString());
        }
    }//GEN-LAST:event_lblOpenRawFileMousePressed

    private void lblFormatGraphMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFormatGraphMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFormatGraphMouseClicked

    private void lblFormatGraphMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFormatGraphMousePressed
        // TODO add your handling code here:
        Variables.graphPropertiesFrame.setVisible(true);
    }//GEN-LAST:event_lblFormatGraphMousePressed

    private void lblSaveMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveMousePressed
        // parent component of the dialog
        if(Variables.globalXESLogListStrings.isEmpty())
        {
            MessageHelper.Warning("Nothing to save!");
            return;
        }
        
        File workingDirectory = new File(System.getProperty("user.dir"));
            try {
                workingDirectory = OpenRecently.GetWorkingDirectory();
            } catch (IOException ex) {
                System.err.println(ex.toString());
            }
        JFrame parentFrame = new JFrame();
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(workingDirectory);
        fileChooser.setDialogTitle("Specify a file to save");   
        File fileToSave = new File(Variables.logName.replace(".xes", Variables.newFileExtension));
        fileChooser.setSelectedFile(fileToSave);
        int userSelection = fileChooser.showSaveDialog(parentFrame);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            fileToSave = new File(fileChooser.getSelectedFile().getAbsoluteFile().toString());
            ThreadController.SaveFileController saveFileController = new SaveFileController(globalXESLogListStrings, fileToSave);
            Thread runSave = new Thread(saveFileController);
            runSave.run();
        }
    }//GEN-LAST:event_lblSaveMousePressed

    private void lblFunctionManagerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFunctionManagerMousePressed
            
            DisplayFunctionList();
            functionManagerFrame.setVisible(true);
       
    }//GEN-LAST:event_lblFunctionManagerMousePressed

    private void lblFunctionManagerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFunctionManagerMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFunctionManagerMouseClicked

    private void lblTraindModelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTraindModelMousePressed
        try {
            // TODO add your handling code here:
            LeftPanelHelper.ViewTraindModel();
        } catch (SQLException ex) {
            Logger.getLogger(LeftPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblTraindModelMousePressed

    private void lblTraindModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTraindModelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTraindModelMouseClicked

    private void lblViewSNAWindowsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewSNAWindowsMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblViewSNAWindowsMouseClicked

    private void lblViewSNAWindowsMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblViewSNAWindowsMousePressed
        // TODO add your handling code here:
        if(!true)
        {
            MessageHelper.Warning("Function is under construction...");
            return;
        }
        
        if(Variables.globalGraph.getNodeCount() == 0)
        {
            MessageHelper.Warning("Nothing to analyze!");
            return;
        }
        frmSNA =  new SNAFrame();
        frmSNA.setVisible(true);
        if(SystemProperties.cbHideStartEndNode.isSelected())
            RemoveStartEndNode(globalGraph);
        
        ThreadController.CalculateGraphCentrality threadCalculate = new CalculateGraphCentrality();
        Thread thisThread = new Thread(threadCalculate);
        thisThread.start();
        
        
        
        
//        SNAHelper.FormatGraph.SetDefaultStyle(Variables.globalGraph);
        
        try {
            FormatGraph.FormatNodeOnDegree(Variables.globalGraph, "Degree");
        } catch (InterruptedException ex) {
            Logger.getLogger(LeftPanel.class.getName()).log(Level.SEVERE, null, ex);
        }

                
    }//GEN-LAST:event_lblViewSNAWindowsMousePressed

    public static void RemoveStartEndNode(Graph graph)
    {
        graph.removeNode("START");
        graph.removeNode("END");
    }
    private void lblOpenrecentlyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenrecentlyMousePressed
        // TODO add your handling code here:
        File workingDirectory = new File(System.getProperty("user.dir"));
        
        try {
            workingDirectory = OpenRecently.GetWorkingDirectory();
            
            LeftPanelHelper.rawFileName = workingDirectory.getAbsolutePath();
            Variables.logName = workingDirectory.getName();

            ThreadController.ReadFileController readFileController = new ReadFileController();
            Thread threadReadFile = new Thread(readFileController);
            threadReadFile.start();
            
            
        } catch (IOException ex) {
            System.err.println(ex.toString());
        }
    }//GEN-LAST:event_lblOpenrecentlyMousePressed

    private void lblOpenrecentlyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOpenrecentlyMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblOpenrecentlyMouseClicked

    private void icnDiscoveryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icnDiscoveryMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_icnDiscoveryMouseClicked

    private void icnDiscoveryMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icnDiscoveryMousePressed
        FormTemplate.ICNDiscovery frmICNDiscovery = new ICNDiscovery();
        frmICNDiscovery.setVisible(true);
    }//GEN-LAST:event_icnDiscoveryMousePressed

    private void advanceGraphViewMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advanceGraphViewMousePressed
        // TODO add your handling code here:
        FormTemplate.AdvanceGraphMining frmAdvanceGraphMining = new AdvanceGraphMining();
        frmAdvanceGraphMining.setVisible(true);
    }//GEN-LAST:event_advanceGraphViewMousePressed

    private void advanceGraphViewMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_advanceGraphViewMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_advanceGraphViewMouseClicked

    private void lblExprotESNMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblExprotESNMousePressed
        // TODO add your handling code here:
        LeftPanelHelper.ExportESN(globalGraph);
    }//GEN-LAST:event_lblExprotESNMousePressed
    
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel advanceGraphView;
    private javax.swing.JLabel icnDiscovery;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lblExprotESN;
    private javax.swing.JLabel lblFormatGraph;
    private javax.swing.JLabel lblFunctionManager;
    private javax.swing.JLabel lblOpenRawFile;
    public static javax.swing.JLabel lblOpenrecently;
    public static javax.swing.JLabel lblSave;
    private javax.swing.JLabel lblTraindModel;
    private javax.swing.JLabel lblViewSNAWindows;
    public static javax.swing.JProgressBar systemProcessingBar;
    // End of variables declaration//GEN-END:variables

    
}
