/*
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTemplate;

import Helper.Common.MessageHelper;
import Helper.Common.Variables;
import static Helper.Dashboard.DetailPanel1Helper.DisplayTotalRow;
import Helper.Dashboard.DetailPanel2Helper;
import TableHelper.TableController;
import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamdinhlam
 */
public class DetailPanel2 extends javax.swing.JPanel {

    /**
     * Creates new form detailPanel1
     */
    public DetailPanel2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cmbSelectTable = new javax.swing.JComboBox<>();
        lblFilterTrace = new javax.swing.JLabel();
        lblClearFilter = new javax.swing.JLabel();
        cbAndFilter = new javax.swing.JCheckBox();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDetailSummary = new javax.swing.JTable();

        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(102, 204, 255)), "Activity/Performer information"));

        cmbSelectTable.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        cmbSelectTable.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Activity", "Performer" }));
        cmbSelectTable.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbSelectTableItemStateChanged(evt);
            }
        });
        cmbSelectTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbSelectTableActionPerformed(evt);
            }
        });
        cmbSelectTable.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbSelectTablePropertyChange(evt);
            }
        });

        lblFilterTrace.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblFilterTrace.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-filter.png"))); // NOI18N
        lblFilterTrace.setText("Filter");
        lblFilterTrace.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFilterTrace.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFilterTraceMousePressed(evt);
            }
        });

        lblClearFilter.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        lblClearFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-clear_filters.png"))); // NOI18N
        lblClearFilter.setText("Clear");
        lblClearFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClearFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblClearFilterMousePressed(evt);
            }
        });

        cbAndFilter.setFont(new java.awt.Font("Lucida Grande", 0, 11)); // NOI18N
        cbAndFilter.setText("And");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(cmbSelectTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbAndFilter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblFilterTrace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblClearFilter)
                .addContainerGap(10, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cmbSelectTable, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbAndFilter))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblFilterTrace)
                            .addComponent(lblClearFilter))
                        .addContainerGap())))
        );

        tblDetailSummary.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "InTotalTrace", "Occurence", "Duration"
            }
        ));
        jScrollPane1.setViewportView(tblDetailSummary);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 404, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cmbSelectTableItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbSelectTableItemStateChanged
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbSelectTableItemStateChanged

    private void cmbSelectTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbSelectTableActionPerformed
        // TODO add your handling code here:
        TableController.ViewTableInDetailPanel(cmbSelectTable.getSelectedItem().toString());
    }//GEN-LAST:event_cmbSelectTableActionPerformed

    private void cmbSelectTablePropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbSelectTablePropertyChange
        // TODO add your handling code here:

    }//GEN-LAST:event_cmbSelectTablePropertyChange

    private void lblFilterTraceMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFilterTraceMousePressed
        // TODO add your handling code here:
        try {
            int[] selectedRowArr = tblDetailSummary.getSelectedRows();
            List<String> nameList = new LinkedList<>();
            for(Integer i=0; i<selectedRowArr.length; i++)
            {
                String _viewingName = tblDetailSummary.getValueAt(selectedRowArr[i], 0).toString();
                nameList.add(_viewingName);
            }
            
            
            if(Variables.currentViewTable.equals("Activity"))
                DetailPanel2Helper.FilterTraceByMemberName(nameList, Variables.globalActWithTraceMap, DetailPanel1.tblTraceSummary, cbAndFilter.isSelected());
            
            if(Variables.currentViewTable.equals("Performer"))
                DetailPanel2Helper.FilterTraceByMemberName(nameList, Variables.globalPerWithTraceMap, DetailPanel1.tblTraceSummary, cbAndFilter.isSelected());
            
            DisplayTotalRow();
            
        } catch (Exception e) {
            MessageHelper.Error(e.toString());
        }
         
                
        
    }//GEN-LAST:event_lblFilterTraceMousePressed

    private void lblClearFilterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearFilterMousePressed
        // TODO add your handling code here:
        DetailPanel2Helper.ShowAll();
    }//GEN-LAST:event_lblClearFilterMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox cbAndFilter;
    public static javax.swing.JComboBox<String> cmbSelectTable;
    public static javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel3;
    public static javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblClearFilter;
    public static javax.swing.JLabel lblFilterTrace;
    public static javax.swing.JTable tblDetailSummary;
    // End of variables declaration//GEN-END:variables
}
