/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTemplate;

import Helper.Common.MessageHelper;
import Helper.Dashboard.DetailPanel3Helper;
import Helper.Dashboard.FunctionManagerHelper;
import static Helper.Dashboard.FunctionManagerHelper.DisplayFunctionList;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author phamdinhlam
 */
public class FunctionManager extends javax.swing.JFrame {

    /**
     * Creates new form FunctionManager
     */
    public FunctionManager() throws SQLException {
        initComponents();
        Initialize();
    }
    public void Initialize() throws SQLException
    {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
//        this.setResizable(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFuncList = new javax.swing.JTable();
        lblCallFunction = new javax.swing.JLabel();
        lblDeleteFunction = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtFuncPara = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtFuncDescribe = new javax.swing.JTextArea();
        txtFuncId = new javax.swing.JTextField();
        txtFuncName = new javax.swing.JTextField();
        lblInsertFunc = new javax.swing.JLabel();
        lblSaveFunc = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tblFuncList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblFuncList);

        lblCallFunction.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblCallFunction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-right.png"))); // NOI18N
        lblCallFunction.setText("Run");
        lblCallFunction.setToolTipText("Format graph in main dashboard");
        lblCallFunction.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblCallFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblCallFunction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCallFunction.setIconTextGap(1);
        lblCallFunction.setName(""); // NOI18N
        lblCallFunction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCallFunction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblCallFunctionMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCallFunctionMouseClicked(evt);
            }
        });

        lblDeleteFunction.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblDeleteFunction.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-minus2.png"))); // NOI18N
        lblDeleteFunction.setText("Remove");
        lblDeleteFunction.setToolTipText("Format graph in main dashboard");
        lblDeleteFunction.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblDeleteFunction.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblDeleteFunction.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDeleteFunction.setIconTextGap(1);
        lblDeleteFunction.setName(""); // NOI18N
        lblDeleteFunction.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblDeleteFunction.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblDeleteFunctionMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDeleteFunctionMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCallFunction, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 326, Short.MAX_VALUE)
                        .addComponent(lblDeleteFunction))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 390, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblDeleteFunction, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lblCallFunction)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 16, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        jLabel1.setText("Id");

        jLabel3.setText("Name");

        jLabel4.setText("Parameter");

        txtFuncPara.setColumns(20);
        txtFuncPara.setLineWrap(true);
        txtFuncPara.setRows(5);
        jScrollPane2.setViewportView(txtFuncPara);

        jLabel5.setText("Describe");

        txtFuncDescribe.setColumns(20);
        txtFuncDescribe.setLineWrap(true);
        txtFuncDescribe.setRows(5);
        jScrollPane3.setViewportView(txtFuncDescribe);

        txtFuncId.setEnabled(false);

        txtFuncName.setEnabled(false);

        lblInsertFunc.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblInsertFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-plus.png"))); // NOI18N
        lblInsertFunc.setText("New");
        lblInsertFunc.setToolTipText("Format graph in main dashboard");
        lblInsertFunc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblInsertFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblInsertFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblInsertFunc.setIconTextGap(1);
        lblInsertFunc.setName(""); // NOI18N
        lblInsertFunc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblInsertFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblInsertFuncMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInsertFuncMouseClicked(evt);
            }
        });

        lblSaveFunc.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblSaveFunc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-save2.png"))); // NOI18N
        lblSaveFunc.setText("Save");
        lblSaveFunc.setToolTipText("Format graph in main dashboard");
        lblSaveFunc.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblSaveFunc.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSaveFunc.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSaveFunc.setIconTextGap(1);
        lblSaveFunc.setName(""); // NOI18N
        lblSaveFunc.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSaveFunc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblSaveFuncMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSaveFuncMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFuncName)
                            .addComponent(txtFuncId)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 523, Short.MAX_VALUE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(lblInsertFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(lblSaveFunc, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(jScrollPane3))))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFuncId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtFuncName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblInsertFunc, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblSaveFunc, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblCallFunctionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCallFunctionMousePressed
        // TODO add your handling code here:
//        if(tblFuncList.getSelectedRow() == -1)
//            return;
//        String funcId = tblFuncList.getValueAt(tblFuncList.getSelectedRow(), 0).toString();
//        try {
//            lblCallFunction.setEnabled(false);
//            DetailPanel3Helper.SetRunningFunction(funcId, lblCallFunction);
//        } catch (IOException ex) {
//            Logger.getLogger(FunctionManager.class.getName()).log(Level.SEVERE, null, ex);
//        } catch (SQLException ex) {
//            Logger.getLogger(FunctionManager.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }//GEN-LAST:event_lblCallFunctionMousePressed

    private void lblCallFunctionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCallFunctionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblCallFunctionMouseClicked

    private void lblSaveFuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveFuncMousePressed
        try {
            // TODO add your handling code here:
            FunctionManagerHelper.Save();
        } catch (SQLException ex) {
            Logger.getLogger(FunctionManager.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblSaveFuncMousePressed

    private void lblSaveFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSaveFuncMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSaveFuncMouseClicked

    private void lblInsertFuncMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsertFuncMousePressed
        // TODO add your handling code here:
        FunctionManagerHelper.InsertNewFunc();
    }//GEN-LAST:event_lblInsertFuncMousePressed

    private void lblInsertFuncMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInsertFuncMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblInsertFuncMouseClicked

    private void lblDeleteFunctionMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteFunctionMousePressed
        try {
             int input = JOptionPane.showConfirmDialog(null, "This action will remove the seleted function. Are you sure?");
            // 0=yes, 1=no, 2=cancel
            if(input == 0)
                FunctionManagerHelper.RemoveFunction();
        } catch (SQLException ex) {
            Logger.getLogger(FunctionManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_lblDeleteFunctionMousePressed

    private void lblDeleteFunctionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDeleteFunctionMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblDeleteFunctionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FunctionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FunctionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FunctionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FunctionManager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new FunctionManager().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(FunctionManager.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblCallFunction;
    private javax.swing.JLabel lblDeleteFunction;
    private javax.swing.JLabel lblInsertFunc;
    private javax.swing.JLabel lblSaveFunc;
    public static javax.swing.JTable tblFuncList;
    public static javax.swing.JTextArea txtFuncDescribe;
    public static javax.swing.JTextField txtFuncId;
    public static javax.swing.JTextField txtFuncName;
    public static javax.swing.JTextArea txtFuncPara;
    // End of variables declaration//GEN-END:variables
}
