/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTemplate;

import static FormTemplate.SystemProperties.lblAndGateColor;
import static FormTemplate.SystemProperties.lblLoopGateColor;
import static FormTemplate.SystemProperties.lblOrGateColor;
import GraphStreamCoreHelper.FormatGraphByForm;
import Helper.Common.ToolsHelper;
import Helper.Common.Variables;
import static Helper.Common.Variables.globalGraph;

import static Helper.Common.Variables.steadyGraph;
import static Helper.Dashboard.ICNDiscoveryHelper.GraphShowHideEdgeLabel;
import static Helper.Dashboard.ICNDiscoveryHelper.GraphShowHideNodeLabel;
import static Helper.Dashboard.ICNDiscoveryHelper.ICNDiscovery;
import Helper.GraphStream.ICNChecker;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;
import static Helper.GraphStream.MakeSteadyGraph.RecoveryEssentialEdge;
import Helper.ICN.ICNBuilderV1;
import static Helper.ICN.ICNBuilderV1.FindLoopGate;
import SNAHelper.FormatGraph;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author phamdinhlam
 */
public class ICNDiscovery extends javax.swing.JFrame {

    /**
     * Creates new form ICNDiscovery
     */
    public ICNDiscovery() {
        initComponents();
        Initialize();
    }
    
    public void Initialize() 
    {
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(100, dim.height/2-this.getSize().height/2 - 100);
        this.setResizable(false);
        this.setAlwaysOnTop(true);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnMakeSteadyGraph = new javax.swing.JButton();
        btnRecoverEdge = new javax.swing.JButton();
        discoveryICN = new javax.swing.JButton();
        fillProportionalToGate = new javax.swing.JButton();
        cbShowGateLabel = new javax.swing.JCheckBox();
        cbShowNodeLabel = new javax.swing.JCheckBox();
        btnReformatGraph = new javax.swing.JButton();
        cbShowEdgeLabel = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnMakeSteadyGraph.setText("<html><p align=\"center\">1. Create <br>steady graph </p></html>");
        btnMakeSteadyGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMakeSteadyGraphActionPerformed(evt);
            }
        });

        btnRecoverEdge.setText("<html><p align=\"center\">2. Recover <br>essential edge </p></html>");
        btnRecoverEdge.setPreferredSize(new java.awt.Dimension(125, 40));
        btnRecoverEdge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRecoverEdgeActionPerformed(evt);
            }
        });

        discoveryICN.setText("<html><p align=\"center\">3. Disover <br> ICN Model</p></html>");
        discoveryICN.setPreferredSize(new java.awt.Dimension(125, 40));
        discoveryICN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                discoveryICNActionPerformed(evt);
            }
        });

        fillProportionalToGate.setText("<html><p align=\"center\">Fill Proportional</p></html>");
        fillProportionalToGate.setPreferredSize(new java.awt.Dimension(125, 40));
        fillProportionalToGate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fillProportionalToGateActionPerformed(evt);
            }
        });

        cbShowGateLabel.setSelected(true);
        cbShowGateLabel.setText("Gate label");
        cbShowGateLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowGateLabelActionPerformed(evt);
            }
        });

        cbShowNodeLabel.setSelected(true);
        cbShowNodeLabel.setText("Node label");
        cbShowNodeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowNodeLabelActionPerformed(evt);
            }
        });

        btnReformatGraph.setText("Reformat graph");
        btnReformatGraph.setPreferredSize(new java.awt.Dimension(125, 40));
        btnReformatGraph.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReformatGraphActionPerformed(evt);
            }
        });

        cbShowEdgeLabel.setSelected(true);
        cbShowEdgeLabel.setText("Edge label");
        cbShowEdgeLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbShowEdgeLabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnMakeSteadyGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRecoverEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(discoveryICN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(cbShowNodeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(cbShowGateLabel))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(cbShowEdgeLabel))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnReformatGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fillProportionalToGate, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(discoveryICN, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnMakeSteadyGraph, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnRecoverEdge, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fillProportionalToGate, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnReformatGraph, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbShowGateLabel)
                    .addComponent(cbShowNodeLabel)
                    .addComponent(cbShowEdgeLabel))
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 16)); // NOI18N
        jLabel1.setText("Discover the Information control net model");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 362, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRecoverEdgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecoverEdgeActionPerformed
        // TODO add your handling code here:

        RecoveryEssentialEdge(steadyGraph, globalGraph);
    }//GEN-LAST:event_btnRecoverEdgeActionPerformed

    private void discoveryICNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_discoveryICNActionPerformed
        // TODO add your handling code here:
        //nodeOccurenceMap steadGraph
        String andGateColor= ToolsHelper.ColortoHexString(lblAndGateColor.getForeground());
        String orGateColor = ToolsHelper.ColortoHexString(lblOrGateColor.getForeground());
        String loopGateColor = ToolsHelper.ColortoHexString(lblLoopGateColor.getForeground());
        Helper.ICN.ICNBuilderV1.BuildICN(steadyGraph, Variables.nodeOccurenceMap, andGateColor, orGateColor, loopGateColor);
        
        FormatGraphByForm.Formatting(steadyGraph);

    }//GEN-LAST:event_discoveryICNActionPerformed

    private void btnMakeSteadyGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMakeSteadyGraphActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            ICNDiscovery();
        } catch (InterruptedException ex) {
            Logger.getLogger(LeftPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnMakeSteadyGraphActionPerformed

    private void fillProportionalToGateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fillProportionalToGateActionPerformed
        // TODO add your handling code here:
        ICNBuilderV1.FillProportionalToGate(steadyGraph, Variables.nodeOccurenceMap);
    }//GEN-LAST:event_fillProportionalToGateActionPerformed

    private void cbShowGateLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowGateLabelActionPerformed
        // TODO add your handling code here:
       GraphShowHideNodeLabel(steadyGraph, cbShowNodeLabel.isSelected(), cbShowGateLabel.isSelected());
    }//GEN-LAST:event_cbShowGateLabelActionPerformed

    private void cbShowNodeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowNodeLabelActionPerformed
        // TODO add your handling code here:
         GraphShowHideNodeLabel(steadyGraph, cbShowNodeLabel.isSelected(), cbShowGateLabel.isSelected());
    }//GEN-LAST:event_cbShowNodeLabelActionPerformed

    private void btnReformatGraphActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReformatGraphActionPerformed
        // TODO add your handling code here:
        FormatGraphByForm.Formatting(steadyGraph);
    }//GEN-LAST:event_btnReformatGraphActionPerformed

    private void cbShowEdgeLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbShowEdgeLabelActionPerformed
        // TODO add your handling code here:
        GraphShowHideEdgeLabel(steadyGraph, cbShowEdgeLabel.isSelected());
    }//GEN-LAST:event_cbShowEdgeLabelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ICNDiscovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ICNDiscovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ICNDiscovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ICNDiscovery.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ICNDiscovery().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMakeSteadyGraph;
    private javax.swing.JButton btnRecoverEdge;
    private javax.swing.JButton btnReformatGraph;
    private javax.swing.JCheckBox cbShowEdgeLabel;
    private javax.swing.JCheckBox cbShowGateLabel;
    private javax.swing.JCheckBox cbShowNodeLabel;
    private javax.swing.JButton discoveryICN;
    private javax.swing.JButton fillProportionalToGate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
