/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTemplate;

import Helper.Common.MessageHelper;
import Helper.Common.Variables;
import java.awt.Color;
import javax.swing.JColorChooser;
import static Helper.Common.Variables.*;
import static Helper.Dashboard.DetailPanel1Helper.CreateTraceSummaryTable;
import Helper.Dashboard.LeftPanelHelper;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.parsers.ParserConfigurationException;
import org.xml.sax.SAXException;
/**
 *
 * @author phamdinhlam
 */
public class SystemProperties extends javax.swing.JFrame {

    /**
     * Creates new form Warning
     */
    public SystemProperties() {
        initComponents();
        Initialize();
    }
    
    public static void Initialize()
    {
        txtTotalRowPerPage.setText(tableSizeLimit.toString());
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        cmbActNodeType = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        cmbStartEndType = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        cmbPerNodeType = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        cmbGateType = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cmbNodeSize = new javax.swing.JComboBox<>();
        lblBackGroundColor = new javax.swing.JLabel();
        lblStartEndNodeColor = new javax.swing.JLabel();
        lblNormalNodeColor = new javax.swing.JLabel();
        lblEdgeColor = new javax.swing.JLabel();
        lblOrGateColor = new javax.swing.JLabel();
        lblAndGateColor = new javax.swing.JLabel();
        lblLoopGateColor = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        cmbGateSize = new javax.swing.JComboBox<>();
        btnGraphVizformat = new javax.swing.JButton();
        cbSkipSelfLoopInSNA = new javax.swing.JCheckBox();
        cbHideStartEndNode = new javax.swing.JCheckBox();
        btnSaveAndClose = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTotalRowPerPage = new javax.swing.JTextField();
        cbUpdateNow = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        jLabel1.setText("Set up system properties");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Graph visualization"));

        jLabel7.setText("Activity node type:");

        cmbActNodeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "circle", "box", "rounded-box", "diamond", "cross", "diamond", "triangle" }));

        jLabel8.setText("{Start, End} node type:");

        cmbStartEndType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "circle", "box", "rounded-box", "diamond", "cross" }));
        cmbStartEndType.setSelectedIndex(4);

        jLabel9.setText("Performer node type:");

        cmbPerNodeType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "circle", "box", "rounded-box", "diamond", "cross", "diamond", "triangle" }));

        jLabel10.setText("Gate type:");

        cmbGateType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "circle", "box", "rounded-box", "diamond", "cross", "diamond", "triangle" }));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cmbStartEndType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbPerNodeType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmbActNodeType, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbGateType, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmbActNodeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(cmbPerNodeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbStartEndType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(cmbGateType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jLabel5.setText("Node size");

        cmbNodeSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tiny", "script", "footnote", "small", "normal", "large", "huge", "gigantic" }));
        cmbNodeSize.setSelectedIndex(2);
        cmbNodeSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbNodeSizeActionPerformed(evt);
            }
        });

        lblBackGroundColor.setForeground(new java.awt.Color(255, 255, 255));
        lblBackGroundColor.setText("Back ground color");
        lblBackGroundColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblBackGroundColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblBackGroundColorMousePressed(evt);
            }
        });

        lblStartEndNodeColor.setForeground(new java.awt.Color(255, 153, 51));
        lblStartEndNodeColor.setText("{Start, End} color");
        lblStartEndNodeColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStartEndNodeColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblStartEndNodeColorMousePressed(evt);
            }
        });

        lblNormalNodeColor.setForeground(new java.awt.Color(4, 140, 140));
        lblNormalNodeColor.setText("Normal node color");
        lblNormalNodeColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblNormalNodeColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblNormalNodeColorMousePressed(evt);
            }
        });

        lblEdgeColor.setForeground(new java.awt.Color(0, 102, 255));
        lblEdgeColor.setText("Edge color");
        lblEdgeColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblEdgeColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblEdgeColorMousePressed(evt);
            }
        });

        lblOrGateColor.setForeground(new java.awt.Color(0, 204, 0));
        lblOrGateColor.setText("Or gate color");
        lblOrGateColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblOrGateColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblOrGateColorMousePressed(evt);
            }
        });

        lblAndGateColor.setText("And gate color");
        lblAndGateColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblAndGateColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblAndGateColorMousePressed(evt);
            }
        });

        lblLoopGateColor.setForeground(new java.awt.Color(102, 0, 0));
        lblLoopGateColor.setText("Loop gate color");
        lblLoopGateColor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblLoopGateColor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblLoopGateColorMousePressed(evt);
            }
        });

        jLabel6.setText("Gate size");

        cmbGateSize.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Level 1", "Level 2", "Level 3", "Level 4", "Level 5" }));
        cmbGateSize.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbGateSizeActionPerformed(evt);
            }
        });

        btnGraphVizformat.setText("Graphviz format");
        btnGraphVizformat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGraphVizformatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblBackGroundColor)
                            .addComponent(lblNormalNodeColor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStartEndNodeColor, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAndGateColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblOrGateColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblLoopGateColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(14, 14, 14)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel6)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(107, 107, 107)
                                            .addComponent(cmbGateSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addGap(107, 107, 107)
                                            .addComponent(cmbNodeSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(lblEdgeColor)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnGraphVizformat)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbNodeSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(cmbGateSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblBackGroundColor)
                    .addComponent(lblAndGateColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNormalNodeColor)
                    .addComponent(lblOrGateColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblStartEndNodeColor)
                    .addComponent(lblLoopGateColor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblEdgeColor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnGraphVizformat))
        );

        cbSkipSelfLoopInSNA.setText("Skip self-loop");

        cbHideStartEndNode.setText("Hide Start, End node");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 26, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbHideStartEndNode)
                    .addComponent(cbSkipSelfLoopInSNA))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cbSkipSelfLoopInSNA)
                        .addGap(18, 18, 18)
                        .addComponent(cbHideStartEndNode))))
        );

        btnSaveAndClose.setText("Save and Close");
        btnSaveAndClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveAndCloseActionPerformed(evt);
            }
        });

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Table setting"));

        jLabel2.setText("Total row per page");

        cbUpdateNow.setText("Update now");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTotalRowPerPage, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cbUpdateNow)
                .addGap(0, 246, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtTotalRowPerPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbUpdateNow))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 411, Short.MAX_VALUE)
                        .addComponent(btnSaveAndClose)
                        .addGap(35, 35, 35))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 325, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(111, 111, 111))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSaveAndClose)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblBackGroundColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblBackGroundColorMousePressed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLUE);
        if (c != null)
        {
            lblBackGroundColor.setForeground(c);
        }
    }//GEN-LAST:event_lblBackGroundColorMousePressed

    private void lblStartEndNodeColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblStartEndNodeColorMousePressed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLUE);
        if (c != null)
        {
            lblStartEndNodeColor.setForeground(c);
        }
    }//GEN-LAST:event_lblStartEndNodeColorMousePressed

    private void lblNormalNodeColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNormalNodeColorMousePressed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLUE);
        if (c != null)
        {
            lblNormalNodeColor.setForeground(c);
        }
    }//GEN-LAST:event_lblNormalNodeColorMousePressed

    private void cmbNodeSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbNodeSizeActionPerformed
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_cmbNodeSizeActionPerformed

    private void lblEdgeColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblEdgeColorMousePressed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLUE);
        if (c != null)
        {
            lblEdgeColor.setForeground(c);
        }
    }//GEN-LAST:event_lblEdgeColorMousePressed

    private void btnSaveAndCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveAndCloseActionPerformed
        // TODO add your handling code here:
        try {
            this.dispose();
            if(cbUpdateNow.isSelected())
            {
                tableSizeLimit = Integer.parseInt(txtTotalRowPerPage.getText());
                LeftPanelHelper.CaculateTotalPage();
                CreateTraceSummaryTable(0);
            }
            
        } catch (Exception e) {
            MessageHelper.Error(e.toString());
        }
        
    }//GEN-LAST:event_btnSaveAndCloseActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
        Integer nodeSize = (cmbNodeSize.getSelectedIndex() + 1) * 5;
        switch (nodeSize)
        {
            case 5:
                styleOffsetForSelfLoop = "text-offset: 10, -10;";
                styleOffsetForAtoB="text-offset: 0, -4;";
                styleOffsetForBtoA="text-offset: 0, 4;";
                break;
            case 10:
                styleOffsetForAtoB="text-offset: 0, -5;";
                styleOffsetForBtoA="text-offset: 0, 5;";
                styleOffsetForSelfLoop = "text-offset: 13, -13;";
                break;
            case 15:
                styleOffsetForAtoB="text-offset: 15, 15;";
                styleOffsetForBtoA="text-offset: -15, -15;";
                styleOffsetForSelfLoop = "text-offset: 25, -25;";
                break;
            case 20: // Small
                styleOffsetForAtoB="text-offset: 0, -20;";
                styleOffsetForBtoA="text-offset: 0, 20;";
                styleOffsetForSelfLoop = "text-offset: 32, -32;";
                break;
            case 25: // Normal
                styleOffsetForSelfLoop = "text-offset: 42, -42;";
                break;
            case 30:
                styleOffsetForSelfLoop = "text-offset: 52, -52;";
                break;
            case 35:
                styleOffsetForSelfLoop = "text-offset: 62, -62;";
                break;
            case 40:
                styleOffsetForSelfLoop = "text-offset: 72, -72;";
                break;
        }
    }//GEN-LAST:event_formWindowClosed

    private void lblOrGateColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblOrGateColorMousePressed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLUE);
        if (c != null)
        {
            lblOrGateColor.setForeground(c);
        }
    }//GEN-LAST:event_lblOrGateColorMousePressed

    private void lblAndGateColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAndGateColorMousePressed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLUE);
        if (c != null)
        {
            lblAndGateColor.setForeground(c);
        }
    }//GEN-LAST:event_lblAndGateColorMousePressed

    private void lblLoopGateColorMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblLoopGateColorMousePressed
        // TODO add your handling code here:
        Color c = JColorChooser.showDialog(null, "Choose a Color", Color.BLUE);
        if (c != null)
        {
            lblLoopGateColor.setForeground(c);
        }
    }//GEN-LAST:event_lblLoopGateColorMousePressed

    private void cmbGateSizeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbGateSizeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbGateSizeActionPerformed

    private void btnGraphVizformatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGraphVizformatActionPerformed
       
            frmGraphviz.setVisible(true);
            this.dispose();
       
    }//GEN-LAST:event_btnGraphVizformatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SystemProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SystemProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SystemProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SystemProperties.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SystemProperties().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnGraphVizformat;
    private javax.swing.JButton btnSaveAndClose;
    public static javax.swing.JCheckBox cbHideStartEndNode;
    public static javax.swing.JCheckBox cbSkipSelfLoopInSNA;
    private javax.swing.JCheckBox cbUpdateNow;
    public static javax.swing.JComboBox<String> cmbActNodeType;
    public static javax.swing.JComboBox<String> cmbGateSize;
    public static javax.swing.JComboBox<String> cmbGateType;
    public static javax.swing.JComboBox<String> cmbNodeSize;
    public static javax.swing.JComboBox<String> cmbPerNodeType;
    public static javax.swing.JComboBox<String> cmbStartEndType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public static javax.swing.JLabel lblAndGateColor;
    public static javax.swing.JLabel lblBackGroundColor;
    public static javax.swing.JLabel lblEdgeColor;
    public static javax.swing.JLabel lblLoopGateColor;
    public static javax.swing.JLabel lblNormalNodeColor;
    public static javax.swing.JLabel lblOrGateColor;
    public static javax.swing.JLabel lblStartEndNodeColor;
    public static javax.swing.JTextField txtTotalRowPerPage;
    // End of variables declaration//GEN-END:variables
}
