/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FormTemplate;

import Helper.Dashboard.TrainedModelHelper;
import static Helper.Dashboard.TrainedModelHelper.ClearFilter;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author phamdinhlam
 */
public class TrainedModel extends javax.swing.JFrame {

    /**
     * Creates new form TraindModel
     */
    public TrainedModel() {
        initComponents();
        this.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
        this.setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTraindModel = new javax.swing.JLabel();
        lblFilter = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        cmbLogName = new javax.swing.JComboBox<>();
        lblClearFilter = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrainedModel = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTraindModel.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblTraindModel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-ms_excel.png"))); // NOI18N
        lblTraindModel.setText("Export");
        lblTraindModel.setToolTipText("View trained model");
        lblTraindModel.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblTraindModel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblTraindModel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblTraindModel.setIconTextGap(1);
        lblTraindModel.setName(""); // NOI18N
        lblTraindModel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblTraindModel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblTraindModelMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblTraindModelMouseClicked(evt);
            }
        });

        lblFilter.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-filter.png"))); // NOI18N
        lblFilter.setText("Filter");
        lblFilter.setToolTipText("View trained model");
        lblFilter.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblFilter.setIconTextGap(1);
        lblFilter.setName(""); // NOI18N
        lblFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblFilterMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFilterMouseClicked(evt);
            }
        });

        jLabel1.setText("Log name:");

        cmbLogName.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblClearFilter.setFont(new java.awt.Font("Dialog", 0, 11)); // NOI18N
        lblClearFilter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icon/icons8-clear_filters.png"))); // NOI18N
        lblClearFilter.setText("Clear Filter");
        lblClearFilter.setToolTipText("View trained model");
        lblClearFilter.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        lblClearFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblClearFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblClearFilter.setIconTextGap(1);
        lblClearFilter.setName(""); // NOI18N
        lblClearFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblClearFilter.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lblClearFilterMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblClearFilterMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cmbLogName, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblFilter)
                .addGap(28, 28, 28)
                .addComponent(lblClearFilter)
                .addGap(208, 208, 208)
                .addComponent(lblTraindModel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(cmbLogName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTraindModel, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
            .addComponent(lblClearFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(lblFilter, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tblTrainedModel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTrainedModel);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1034, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblTraindModelMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTraindModelMousePressed
        TrainedModelHelper.ExportToExcel(tblTrainedModel);
    }//GEN-LAST:event_lblTraindModelMousePressed

    private void lblTraindModelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblTraindModelMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTraindModelMouseClicked

    private void lblFilterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFilterMousePressed
        try {
            // TODO add your handling code here:
            TrainedModelHelper.FilterTraindModel(cmbLogName.getSelectedItem().toString());
        } catch (SQLException ex) {
            Logger.getLogger(TrainedModel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblFilterMousePressed

    private void lblFilterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFilterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblFilterMouseClicked

    private void lblClearFilterMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearFilterMousePressed
        try {
            // TODO add your handling code here:
            ClearFilter();
        } catch (SQLException ex) {
            Logger.getLogger(TrainedModel.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_lblClearFilterMousePressed

    private void lblClearFilterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblClearFilterMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblClearFilterMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrainedModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrainedModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrainedModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrainedModel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrainedModel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JComboBox<String> cmbLogName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel lblClearFilter;
    public static javax.swing.JLabel lblFilter;
    private javax.swing.JLabel lblTraindModel;
    public static javax.swing.JTable tblTrainedModel;
    // End of variables declaration//GEN-END:variables
}
